storeApp:
  services:
    catalogue:
      uri: http://localhost:8081
      registrationId: keycloak
server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/storeApp
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: manager-app
            client-secret: LIRsHn3jTQrhAiMuL7wwIWiAQCVmgCqD
            scope:
              - openid
              - view_catalogue
              - edit_catalogue
              - microprofile-jwt

  datasource:
    url: jdbc:postgresql://localhost:5433/manager
    username: postgres
    password: postgres
