
services:
  postgres:
    image: postgres:16
    container_name: postgres_manager
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: manager
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_manager:/var/lib/postgresql/data
    networks:
      - manager_net
    restart: unless-stopped

volumes:
  postgres_data_manager:

networks:
  manager_net:
    driver: bridge